# Ekran ayarları

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Pamukkale Drift"

# Oyun sabitleri

ENGEL_HIZI = 5
HIZ_ARTIS = 0.1

# Şerit sabitleri

SERIT_GENISLIK = 8
SERIT_YUKSEKLIK = 30
SERIT_BOSLUK = 50
SERIT_SAYISI = 4
YOL_GENISLIK = 800
YOL_BASLANGIC = (SCREEN_WIDTH - YOL_GENISLIK) // 2
SERIT_ARASI = YOL_GENISLIK / SERIT_SAYISI

# Şerit ve engel konumları

SERIT_X_KONUMLARI = [YOL_BASLANGIC + (i * SERIT_ARASI) for i in range(1, SERIT_SAYISI)]
ENGEL_KONUMLARI = [YOL_BASLANGIC + (i * SERIT_ARASI) - (SERIT_ARASI / 2) for i in range(1, SERIT_SAYISI + 1)]